### PR TITLE
Bump go.opentelemetry.io/otel to v0.5.0.

### LINKED ISSUE #17: update to v0.4.3 compat
```
# github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace
../pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/trace@v0.1.0/trace_proto.go:67:32: s.SpanContext.TraceIDString undefined (type core.SpanContext has no field or method TraceIDString)
../pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/trace@v0.1.0/trace_proto.go:68:31: s.SpanContext.SpanIDString undefined (type core.SpanContext has no field or method SpanIDString)
```

### PR DESCRIPTION
**Pull request by charleskorn**
v0.4.3 contains a breaking change that removes the `TraceIDString()` and `SpanIDString()` functions (https://github.com/open-telemetry/opentelemetry-go/pull/642).

v0.5.0 moved the `Key` and `KeyValue` types to a new package. There may be other changes required for this library to work correctly with v0.5.0 - I only made enough changes to fix the compilation errors. (Having said that, a cursory glance over the remaining changes in `otel` don't appear to require further changes here.)

One other thing I noticed was that `attributeValue()` in `trace_proto.go` silently ignores other kinds of values (eg. `INT32`, `UINT32`, `FLOAT32`) - is this intentional? I would hope that this library would loudly complain if I used a type of attribute it didn't support rather than quietly dropping it.

Fixes #17.

### CODE REVIEW

**Comment by avarghese-sqsp** [comment]
I have this error
```
# github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace
app_1       | /go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/trace@v0.1.0/trace_proto.go:67:32: s.SpanContext.TraceIDString undefined (type core.SpanContext has no field or method TraceIDString)
```

with v0.4.3

**Comment by lizthegrey** [comment]
Thank you!
